# Generated by Django 6.0.3 on 2026-03-22 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('banda', 'Banda'), ('cantor', 'Cantor Solo'), ('folclorico', 'Grupo Folclórico'), ('orquestra', 'Orquestra'), ('danca', 'Grupo de Dança'), ('teatro', 'Teatro')], max_length=20, verbose_name='Tipo')),
                ('cidade_origem', models.CharField(max_length=100, verbose_name='Cidade de Origem')),
                ('uf_origem', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('tipo', models.CharField(choices=[('sao_joao', 'São João'), ('natal', 'Natal'), ('carnaval', 'Carnaval'), ('inverno', 'Festival de Inverno'), ('aniversario', 'Aniversário da Cidade'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Término')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('funcao', models.CharField(choices=[('coordenador', 'Coordenador'), ('tecnico_som', 'Técnico de Som'), ('tecnico_palco', 'Técnico de Palco'), ('apoio', 'Apoio'), ('seguranca', 'Segurança'), ('outro', 'Outro')], max_length=20, verbose_name='Função')),
                ('contato', models.CharField(max_length=100, verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade (pessoas)')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('zona', models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=10, verbose_name='Zona')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polos', to='core.pessoa', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Polo',
                'verbose_name_plural': 'Polos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('valor_cache', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Cachê (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atracao', verbose_name='Atração')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento', verbose_name='Evento')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.polo', verbose_name='Polo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
