# Generated by Django 6.0.3 on 2026-03-23 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_ativo_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['data', 'horario_inicio'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='horario',
        ),
        migrations.AddField(
            model_name='contrato',
            name='horario_fim',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário de Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='horario_inicio',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário de Início'),
            preserve_default=False,
        ),
    ]
