# Generated by Django 5.2.12 on 2026-03-23 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_horario_inicio_fim'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('observacao', models.CharField(blank=True, help_text='Ex: "Reservado para headliner", "Abertura"', max_length=200, verbose_name='Observação')),
                ('contrato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='core.contrato', verbose_name='Contrato (Atração)')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.evento', verbose_name='Evento')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.polo', verbose_name='Polo')),
            ],
            options={
                'verbose_name': 'Slot de Programação',
                'verbose_name_plural': 'Slots de Programação',
                'ordering': ['data', 'polo__nome', 'horario_inicio'],
                'unique_together': {('evento', 'polo', 'data', 'horario_inicio')},
            },
        ),
    ]
